// Row-major positions match the transparent 6 × 5 atlas; lore is descriptive.
const entries = [
  ['dong-diep-thao', 'Đồng Diệp Thảo', 'common', 'Ba lá đỏ đồng khẽ rung khi linh khí trong đất chuyển mùa.'],
  ['kim-sa-lo-thao', 'Kim Sa Lộ Thảo', 'common', 'Ngọn cỏ giữ những giọt sương vàng đến tận giữa trưa.'],
  ['ngoc-tam-lan', 'Ngọc Tâm Lan', 'uncommon', 'Cánh lan ngà ôm một nhụy tròn sáng như hạt kim châu.'],
  ['kim-quyen-quyet', 'Kim Quyển Quyết', 'uncommon', 'Lá dương xỉ vàng cuộn thành vòng nhỏ bên vách cổ điện.'],
  ['dong-tu-can', 'Đồng Tu Căn', 'uncommon', 'Củ đất vàng có chùm rễ mảnh mang sắc đồng cũ.'],
  ['co-dong-co', 'Cổ Đồng Cô', 'common', 'Cụm nấm màu đồng thường mọc cạnh rễ cây lâu năm.'],
  ['long-lan-diep', 'Long Lân Diệp', 'rare', 'Lá ngọc xếp chồng tựa vảy rồng, sáng lên sau cơn mưa.'],
  ['long-giac-hoa', 'Long Giác Hoa', 'rare', 'Hoa đỏ có nhụy cong như sừng linh long trong truyền thuyết.'],
  ['phuong-vu-quyet', 'Phượng Vũ Quyết', 'rare', 'Tán lá vàng thanh mảnh trông như chiếc lông phượng đang xòe.'],
  ['phuong-vi-hoa', 'Phượng Vĩ Hoa', 'epic', 'Đóa hoa cam đỏ mở thành đuôi phượng lúc mặt trời xuống núi.'],
  ['long-trao-can', 'Long Trảo Căn', 'rare', 'Rễ xanh chia năm nhánh cong, bám sâu trong những khe đá ấm.'],
  ['kim-hoan-chi', 'Kim Hoàn Chi', 'rare', 'Mũ linh chi đỏ có vòng vàng nối tiếp như tuổi của cổ thụ.'],
  ['sa-phong-thao', 'Sa Phong Thảo', 'common', 'Cỏ xanh xám đứng vững giữa cát nhờ những phiến lá hẹp.'],
  ['ho-phach-sa-lien', 'Hổ Phách Sa Liên', 'uncommon', 'Lá mọng có gai nhỏ nâng đóa hoa hổ phách trên cồn cát.'],
  ['sa-nham-sam', 'Sa Nham Sâm', 'uncommon', 'Linh sâm màu sa thạch giấu phần củ dưới lớp cát nguội.'],
  ['tu-sa-hoa', 'Tử Sa Hoa', 'rare', 'Hoa tím nhỏ với lá vàng nhạt chỉ nở sau mưa trên sa mạc.'],
  ['dong-dang-qua', 'Đồng Đăng Quả', 'uncommon', 'Vỏ quả khô màu đồng bao lấy hạt như những chiếc đèn lồng.'],
  ['bach-sa-linh-hoa', 'Bạch Sa Linh Hoa', 'rare', 'Hoa trắng hồng mọc từ rễ xoắn, tìm nguồn nước dưới cát sâu.'],
  ['mo-chung-hoa', 'Mộ Chung Hoa', 'uncommon', 'Những chuông hoa tím khép lại khi tia nắng cuối cùng tắt.'],
  ['ngan-tieu-lan', 'Ngân Tiêu Lan', 'rare', 'Lan lam đậm có đầu cánh bạc, nổi rõ dưới bầu trời chạng vạng.'],
  ['hoang-hon-co', 'Hoàng Hôn Cô', 'uncommon', 'Nấm tím có phiến vàng ấm như ánh chiều còn đọng dưới tán rừng.'],
  ['da-chau-lien', 'Dạ Châu Liên', 'epic', 'Sen màu mận ôm hạt ngà sáng dịu trong lòng hoa.'],
  ['tu-kim-quyet', 'Tử Kim Quyết', 'rare', 'Lá tím uốn cong bảo vệ những chồi vàng khỏi sương đêm.'],
  ['ngan-nguyet-diep', 'Ngân Nguyệt Diệp', 'rare', 'Lá mọng bạc cong như lưỡi trăng, mọc thành một tán thấp.'],
  ['kim-tinh-giap', 'Kim Tinh Giáp', 'rare', 'Vỏ hạt vàng năm cánh xòe như ngôi sao trên cuống xanh.'],
  ['van-dong-linh-qua', 'Vân Đồng Linh Quả', 'rare', 'Quả ngọc nhỏ có đường vân đồng cuộn quanh lớp vỏ cứng.'],
  ['luu-ly-ngoc-hoa', 'Lưu Ly Ngọc Hoa', 'epic', 'Cánh hoa ngà mỏng trong ôm những sợi nhụy hổ phách.'],
  ['co-kim-cuc', 'Cổ Kim Cúc', 'rare', 'Hoa cúc vàng nhiều cánh mọc trên cành lá màu đồng trầm.'],
  ['xich-long-linh-qua', 'Xích Long Linh Quả', 'epic', 'Quả đỏ có vảy nhọn, treo ở đầu cuống xoắn như đuôi rồng.'],
  ['tu-kim-thien-lien', 'Tử Kim Thiên Liên', 'epic', 'Tầng cánh sen tím vàng mở trong đêm lặng, phản chiếu ánh sao.'],
]

export const herbsC = entries.map(([id, name, rarity, description], sprite) => ({
  id,
  name,
  kind: 'herb',
  rarity,
  description,
  image: '/assets/items/herbs-v1/group-c.png',
  sprite,
  columns: 6,
  rows: 5,
}))
