// Sprite order matches the generated 8×4 atlas; these herbs are collection entries.
const entries = [
  ['tuyet-linh-linh', 'Tuyết Linh Linh', 'uncommon', 'Ba chuông hoa xanh nhạt rung khẽ giữa màn tuyết.'],
  ['ngan-suong-quyet', 'Ngân Sương Quyết', 'common', 'Dương xỉ bạc cuộn ngọn, giữ sương lạnh trên lá.'],
  ['bach-tuyet-mai', 'Bạch Tuyết Mai', 'rare', 'Cành mai trắng nở năm cánh trên sườn núi phủ tuyết.'],
  ['bang-truc-nha', 'Băng Trúc Nha', 'common', 'Măng trúc lam nhạt có đầu lá đóng một lớp băng mỏng.'],
  ['han-van-chi', 'Hàn Vân Chi', 'rare', 'Tai nấm xếp tầng xanh trắng tựa mây trên đỉnh núi lạnh.'],
  ['tuyet-chau-sam', 'Tuyết Châu Sâm', 'epic', 'Củ sâm trắng ngọc kết tinh linh khí dưới nền tuyết lâu năm.'],
  ['suong-bac-ha', 'Sương Bạc Hà', 'common', 'Bụi bạc hà xanh ngọc có mép lá trắng như sương giá.'],
  ['bang-tam-lien', 'Băng Tâm Liên', 'epic', 'Sen trắng ôm nhụy lam, chỉ nở trên mặt hồ lạnh.'],
  ['kim-loi-thao', 'Kim Lôi Thảo', 'common', 'Cỏ vàng có phiến lá gấp khúc như tia chớp.'],
  ['loi-tam-ke', 'Lôi Tâm Kế', 'uncommon', 'Hoa kế tím mang nhụy vàng sáng sau cơn giông.'],
  ['tu-dien-dang', 'Tử Điện Đằng', 'uncommon', 'Dây leo tím cuộn quanh nụ vàng, lá rung khi trời nổi sấm.'],
  ['ho-phach-loi-lan', 'Hổ Phách Lôi Lan', 'rare', 'Lan màu hổ phách vươn trên thân xanh điện.'],
  ['mac-loi-co', 'Mặc Lôi Cô', 'rare', 'Nấm tím sẫm có vệt vàng gấp khúc trên mũ.'],
  ['kim-dien-khuong', 'Kim Điện Khương', 'uncommon', 'Củ gừng vàng mọc chồi tím nơi đất từng bị sét đánh.'],
  ['xich-dien-hoa', 'Xích Điện Hoa', 'rare', 'Đóa hoa đỏ nổi bật giữa cụm lá lam thẫm.'],
  ['loi-tiet-truc', 'Lôi Tiết Trúc', 'epic', 'Nhánh trúc tím có đốt ánh vàng tích linh lực của giông.'],
  ['nguyet-liem-hoa', 'Nguyệt Liêm Hoa', 'rare', 'Cánh hoa bạc cong như trăng lưỡi liềm.'],
  ['da-tinh-quyet', 'Dạ Tinh Quyết', 'common', 'Dương xỉ lam sẫm có những chấm bạc như sao đêm.'],
  ['bat-tinh-hoa', 'Bát Tinh Hoa', 'uncommon', 'Hoa hồng nhạt xòe tám cánh nhọn thành hình ngôi sao.'],
  ['tinh-ha-linh', 'Tinh Hà Linh', 'uncommon', 'Chuông hoa xanh điểm đốm trắng tựa dòng sao nhỏ.'],
  ['thien-tinh-co', 'Thiên Tinh Cô', 'rare', 'Nấm màu trời đêm mang đốm sao trắng trên mũ.'],
  ['vong-nguyet-sam', 'Vọng Nguyệt Sâm', 'epic', 'Củ sâm tím nâng quả trắng tròn như một vầng trăng.'],
  ['ngan-nguyet-lien-nhuc', 'Ngân Nguyệt Liên Nhục', 'uncommon', 'Lá mọng màu bạc xếp thành một đài sen nhỏ.'],
  ['tam-tinh-dang', 'Tam Tinh Đằng', 'rare', 'Dây leo xanh ngọc treo ba hoa vàng hình ngôi sao.'],
  ['thach-anh-son-thao', 'Thạch Anh Sơn Thảo', 'uncommon', 'Cỏ núi xanh có phiến lá trắng nhọn như thạch anh.'],
  ['son-ngoc-quyet', 'Sơn Ngọc Quyết', 'common', 'Dương xỉ xanh lam bám rễ vào hốc đá xám.'],
  ['tu-tinh-son-hoa', 'Tử Tinh Sơn Hoa', 'rare', 'Đóa hoa tím có cánh góc cạnh tựa tinh thể núi.'],
  ['son-hoang-khuong', 'Sơn Hoàng Khương', 'common', 'Củ gừng vàng đất mang tán lá xanh ngọc bích.'],
  ['hong-thuy-lien', 'Hồng Thủy Liên', 'uncommon', 'Sen hồng nổi cùng hai lá tròn trên hồ yên.'],
  ['kim-chau-tao', 'Kim Châu Tảo', 'rare', 'Tảo xanh phân nhánh, đầu ngọn đọng những hạt vàng.'],
  ['bich-dam-reu', 'Bích Đàm Rêu', 'common', 'Búi rêu xanh ngọc mọc nụ tím ở ven đầm nước ngọt.'],
  ['lam-ngoc-thuy-lan', 'Lam Ngọc Thủy Lan', 'epic', 'Hoa súng xanh nhạt vươn trên cuống cong như ngọc trong nước.'],
]

export const herbsB = entries.map(([id, name, rarity, description], sprite) => ({
  id, name, kind: 'herb', rarity, description,
  image: '/assets/items/herbs-v1/group-b.png', sprite, columns: 8, rows: 4,
}))
