export const herbsA = [
  {
    "id": "kim-lo-thao",
    "name": "Kim Lộ Thảo",
    "kind": "herb",
    "rarity": "common",
    "description": "Cỏ lá vàng giữ giọt linh lộ lúc bình minh.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 0,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "nguyet-tam-lan",
    "name": "Nguyệt Tâm Lan",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Lan trắng nở khi ánh trăng chạm khe núi.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 1,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "hoa-phuong-hoa",
    "name": "Hỏa Phượng Hoa",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Cánh đỏ cam xòe như đuôi phượng lửa.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 2,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "bich-tuyen-lien",
    "name": "Bích Tuyền Liên",
    "kind": "herb",
    "rarity": "rare",
    "description": "Sen xanh ngọc sinh bên mắt suối yên lặng.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 3,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "han-tinh-mai",
    "name": "Hàn Tinh Mai",
    "kind": "herb",
    "rarity": "rare",
    "description": "Cành mai lam kết hoa giữa sương lạnh.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 4,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "huyet-ngoc-qua",
    "name": "Huyết Ngọc Quả",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Chùm quả đỏ trong như hạt ngọc huyết.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 5,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "phong-linh-diep",
    "name": "Phong Linh Diệp",
    "kind": "herb",
    "rarity": "common",
    "description": "Lá xoắn nghe tiếng gió len qua vách đá.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 6,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "dia-hoang-can",
    "name": "Địa Hoàng Căn",
    "kind": "herb",
    "rarity": "common",
    "description": "Rễ vàng nâu cuộn sâu dưới nền đất ấm.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 7,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "ngan-ti-dang",
    "name": "Ngân Ti Đằng",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Dây bạc uốn thành vòng quanh cành cổ thụ.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 8,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "thanh-vu-duong-xi",
    "name": "Thanh Vũ Dương Xỉ",
    "kind": "herb",
    "rarity": "common",
    "description": "Lá dương xỉ xanh như chiếc lông chim nhỏ.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 9,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "luu-ly-cuc",
    "name": "Lưu Ly Cúc",
    "kind": "herb",
    "rarity": "rare",
    "description": "Cánh cúc lam lấp lánh như lưu ly.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 10,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "tu-diep-lan",
    "name": "Tử Điệp Lan",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Lan tím có cánh tựa bướm đậu trên lá.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 11,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "xich-diem-chi",
    "name": "Xích Diễm Chi",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Tai chi đỏ dựng lên như lưỡi lửa.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 12,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "bach-van-nhi",
    "name": "Bạch Vân Nhĩ",
    "kind": "herb",
    "rarity": "common",
    "description": "Nấm trắng xếp lớp mềm như mây đầu núi.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 13,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "hoang-sa-sam",
    "name": "Hoàng Sa Sâm",
    "kind": "herb",
    "rarity": "rare",
    "description": "Rễ sâm vàng sống trong cát khô giàu linh khí.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 14,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "hac-truc-nha",
    "name": "Hắc Trúc Nha",
    "kind": "herb",
    "rarity": "common",
    "description": "Măng trúc đen phủ lớp ánh xanh nhạt.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 15,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "loi-quang-thao",
    "name": "Lôi Quang Thảo",
    "kind": "herb",
    "rarity": "rare",
    "description": "Cỏ vàng chia nhánh như tia sét nhỏ.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 16,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "suong-ngan-lien",
    "name": "Sương Ngân Liên",
    "kind": "herb",
    "rarity": "rare",
    "description": "Sen bạc ngậm sương nơi hồ núi lạnh.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 17,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "tinh-ha-hoa",
    "name": "Tinh Hà Hoa",
    "kind": "herb",
    "rarity": "epic",
    "description": "Hoa lam đậm có cánh hình ngôi sao.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 18,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "cuu-diep-linh",
    "name": "Cửu Diệp Linh",
    "kind": "herb",
    "rarity": "rare",
    "description": "Chín lá ngọc tụ quanh một cuống nhỏ.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 19,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "long-tu-can",
    "name": "Long Tu Căn",
    "kind": "herb",
    "rarity": "rare",
    "description": "Rễ màu hổ phách phân nhánh như râu rồng.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 20,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "phi-thuy-dang",
    "name": "Phỉ Thúy Đằng",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Dây ngọc xanh đeo lá hình trái tim.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 21,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "hong-nguyet-chi",
    "name": "Hồng Nguyệt Chi",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Tai chi hồng cong thành vầng trăng khuyết.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 22,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "tuyet-phach-qua",
    "name": "Tuyết Phách Quả",
    "kind": "herb",
    "rarity": "rare",
    "description": "Quả trắng phủ lớp sương trong như băng.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 23,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "da-minh-lan",
    "name": "Dạ Minh Lan",
    "kind": "herb",
    "rarity": "rare",
    "description": "Lan xanh nhạt tỏa sáng dưới tán rừng đêm.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 24,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "thai-duong-cuc",
    "name": "Thái Dương Cúc",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Cúc vàng đỏ quay về phía mặt trời sớm.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 25,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "mac-lien-thao",
    "name": "Mặc Liên Thảo",
    "kind": "herb",
    "rarity": "epic",
    "description": "Sen đen có viền tím ở đầu từng cánh.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 26,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "thien-thanh-tung",
    "name": "Thiên Thanh Tùng",
    "kind": "herb",
    "rarity": "uncommon",
    "description": "Nhánh tùng lam mang hương gió trời cao.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 27,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "ngoc-ho-lo",
    "name": "Ngọc Hồ Lô",
    "kind": "herb",
    "rarity": "rare",
    "description": "Quả hồ lô ngọc cuộn mình trong dây lá.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 28,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "chu-sa-diep",
    "name": "Chu Sa Diệp",
    "kind": "herb",
    "rarity": "common",
    "description": "Cành lá đỏ son nổi bật giữa rêu núi.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 29,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "lam-hoa-nhi",
    "name": "Lam Hỏa Nhĩ",
    "kind": "herb",
    "rarity": "rare",
    "description": "Nấm lam có tai vươn như ngọn lửa lạnh.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 30,
    "columns": 8,
    "rows": 4
  },
  {
    "id": "kim-long-sam",
    "name": "Kim Long Sâm",
    "kind": "herb",
    "rarity": "epic",
    "description": "Rễ sâm vàng uốn mình thành dáng rồng.",
    "image": "/assets/items/herbs-v1/group-a.png",
    "sprite": 31,
    "columns": 8,
    "rows": 4
  }
]
